# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "generic/ubuntu2204"

  config.vm.define :dome, primary:true do |dome|
    dome.vm.hostname = "dome.local"
    dome.vm.network "private_network", ip: "192.168.56.3"
    dome.vm.boot_timeout = 300

    dome.vm.provision :file, source: "bootstrap-root.sh", destination: "/home/vagrant/bootstrap-root.sh"
    dome.vm.provision :file, source: "bootstrap-user.sh", destination: "/home/vagrant/bootstrap-user.sh"

    dome.vm.provision :shell, inline: <<-SHELL
      echo "root:dome" | sudo chpasswd
    SHELL

    dome.vm.provision "shell", inline: <<-SHELL
      sudo apt update -y
      sudo apt upgrade -y
      sudo apt install ubuntu-release-upgrader-core
      sudo -i /bin/bash /home/vagrant/bootstrap-root.sh
      sudo reboot
    SHELL

    dome.vm.provision :shell, inline: <<-SHELL
      sleep 120
      sudo -i -u dome /bin/bash /home/vagrant/bootstrap-user.sh
    SHELL

    dome.vm.provider :virtualbox do |vbox|
      vbox.name = "dome"
      vbox.memory = 1024
      vbox.cpus = 2
    end
  end

  config.vm.define :client, primary:true do |client|
    client.vm.hostname = "client.local"
    client.vm.network "private_network", ip: "192.168.56.4"
    # delete default route to nat interface
    client.vm.provision "shell",
      run: "always",
      inline: "ip route del default via 10.0.2.2 && ip route add default via 192.168.56.3 proto dhcp src 192.168.56.4 metric 100 || true"

    client.vm.provider :virtualbox do |vbox|
      vbox.name = "client"
      vbox.memory = 1024
      vbox.cpus = 1
    end
  end
end
