{
 "title": "ring-0 d0me",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "All requests",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "http",
       "query": "SELECT \"action\" FROM \"http\" WHERE $timeFilter",
       "select": [
        [
         { "params": [ "action" ], "type": "field" }
        ]
       ]
      }
     ]
    },
    {
     "title": "Granted",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "http",
       "query": "SELECT \"action\" FROM \"http\" WHERE (\"action\"::field = 'pass') AND $timeFilter",
       "select": [
        [
         { "params": [ "action" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "action::field", "operator": "=", "value": "warn" }
       ]
      }
     ]
    },
    {
     "title": "Blocked",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 10, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "http",
       "select": [
        [
         { "params": [ "action" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "action::field", "operator": "=", "value": "drop" }
       ]
      }
     ]
    },
    {
     "title": "Warnings",
     "type": "stat",
     "gridPos": { "h": 7, "w": 5, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "measurement": "http",
       "select": [
        [
         { "params": [ "action" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "action::field", "operator": "=", "value": "warn" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Blocked requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Categories",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "http",
     "select": [
      [
       { "params": [ "reason" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "action::field", "operator": "=", "value": "drop" }
     ]
    }
   ]
  },
  {
   "title": "Most blocked domains",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 15, "x": 5, "y": 2 },
   "targets": [
    {
     "measurement": "http",
     "query": "SELECT \"domain\" FROM \"http\" WHERE (\"action\"::field = 'drop') AND $timeFilter",
     "select": [
      [
       { "params": [ "domain" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "action::field", "operator": "=", "value": "drop" }
     ]
    }
   ]
  },
  {
   "title": "Blocked requests",
   "type": "barchart",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 12 },
   "targets": [
    {
     "measurement": "http",
     "query": "SELECT \"domain\" FROM \"http\" WHERE (\"action\"::field = 'drop') AND $timeFilter",
     "select": [
      [
       { "params": [ "domain" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "action::field", "operator": "=", "value": "drop" }
     ]
    }
   ]
  },
  { "title": "Granted requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Categories",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "http",
     "query": "SELECT \"reason\" FROM \"http\" WHERE (\"action\"::field = 'pass') AND $timeFilter",
     "select": [
      [
       { "params": [ "reason" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "action::field", "operator": "=", "value": "pass" }
     ]
    }
   ]
  },
  {
   "title": "Non-work related breakdown",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 5, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "http",
     "query": "SELECT \"reason\" FROM \"http\" WHERE (\"action\"::field = 'warn') AND $timeFilter",
     "select": [
      [
       { "params": [ "reason" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "action::field", "operator": "=", "value": "pass" }
     ]
    }
   ]
  },
  {
   "title": "Most accessed domains",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 10, "x": 10, "y": 17 },
   "targets": [
    {
     "measurement": "http",
     "select": [
      [
       { "params": [ "domain" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "action::field", "operator": "=", "value": "pass" }
     ]
    }
   ]
  }
 ]
}