{
 "title": "ring-0 d0me",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Visão Geral",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Distribuição das requisições",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "http",
     "query": "SELECT \"action\" FROM \"http\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "action" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Autorizações",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "http",
     "query": "SELECT \"action\" FROM \"http\" WHERE (\"action\"::field = 'pass') AND $timeFilter",
     "select": [
      [
       { "params": [ "action" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "action::field", "operator": "=", "value": "warn" }
     ]
    }
   ]
  },
  {
   "title": "Bloqueios",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "http",
     "select": [
      [
       { "params": [ "action" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "action::field", "operator": "=", "value": "drop" }
     ]
    }
   ]
  },
  {
   "title": "Alertas",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "http",
     "select": [
      [
       { "params": [ "action" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "action::field", "operator": "=", "value": "warn" }
     ]
    }
   ]
  },
  { "title": "Requisições bloqueadas", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Categorias de bloqueio",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "http",
     "select": [
      [
       { "params": [ "reason" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "action::field", "operator": "=", "value": "drop" }
     ]
    }
   ]
  },
  {
   "title": "Domínios bloqueados",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 9 },
   "targets": [
    {
     "measurement": "http",
     "query": "SELECT \"domain\" FROM \"http\" WHERE (\"action\"::field = 'drop') AND $timeFilter",
     "select": [
      [
       { "params": [ "domain" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "action::field", "operator": "=", "value": "drop" }
     ]
    }
   ]
  },
  {
   "title": "Requisições bloqueadas",
   "type": "barchart",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "measurement": "http",
     "query": "SELECT \"domain\" FROM \"http\" WHERE (\"action\"::field = 'drop') AND $timeFilter",
     "select": [
      [
       { "params": [ "domain" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "action::field", "operator": "=", "value": "drop" }
     ]
    }
   ]
  },
  { "title": "Acessos autorizados", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Categorias",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "http",
     "query": "SELECT \"reason\" FROM \"http\" WHERE (\"action\"::field = 'pass') AND $timeFilter",
     "select": [
      [
       { "params": [ "reason" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "action::field", "operator": "=", "value": "pass" }
     ]
    }
   ]
  },
  {
   "title": "Outros",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "http",
     "query": "SELECT \"reason\" FROM \"http\" WHERE (\"action\"::field = 'warn') AND $timeFilter",
     "select": [
      [
       { "params": [ "reason" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "action::field", "operator": "=", "value": "pass" }
     ]
    }
   ]
  },
  {
   "title": "Domínios autorizados",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "measurement": "http",
     "select": [
      [
       { "params": [ "domain" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "action::field", "operator": "=", "value": "pass" }
     ]
    }
   ]
  }
 ]
}