network:
  version: 2
  ethernets:
    enp0s3:
      dhcp4: false
      addresses:
        - 10.0.6.10/24
      routes:
        - to: default
          via: 10.0.6.1
      nameservers:
        addresses:
          - 1.1.1.1
          - 8.8.8.8
    enp0s8:
      dhcp4: true

